global:
  scrape_interval: 15s
  external_labels:
    role: "receiver"

scrape_configs:
  - job_name: "self"
    scrape_interval: 30s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "avalanche"
    scrape_interval: 30s
    static_configs:
      - targets: ["docker.for.mac.localhost:9001"]
